version: "3.1"
services:
    backend:
        container_name: garage-back
        build: ./backend
        command: npm start
        volumes:
            - .:/code
        ports:
            - "5000:5000"
    frontend:
        container_name: garage-front
        build: ./frontend
        command: npm start
        volumes:
            - .:/usr/src
        ports:
            - "3001:3001"
